server:
  servlet:
    context-path: /springbootfive

spring:
  thymeleaf:
    cache: false
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mydatabase?userUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT
    username: root
    password: accp

mybatis:
  mapper-locations: classpath:mapper/*.xml
